### ISSUE TITLE
Question about Line 470 in DSC_mri_aif.m

### ISSUE THREAD

**Issue by Caffetaria** [aylward/Perfusion-Analysis-Toolbox-OLD#3]
@aylward Lines 466-472 prepare the data contents of the matrix (in MATLAB):
```
ind=find(ROI);
k=nR*nC;
for t=1:nT
       dati2D(:,t)=AIFslice(ind+k*(t-1));
end
maskAIF=ROI;
``` 
I'm not sure why `AIFslice` is being indexed this way, especially since `ind` is a tuple of tensor arrays that looks like this (when converted to python code using pytorch):
`(tensor([67, 67, 67, 67, 68, 70, 70, 72, 78, 78, 83, 84]), tensor([ 22, 109, 110, 114, 114,  23, 106, 108,  65,  72,  76,  72]))`

Dati2D has dimensions: `torch.Size([2, 16])`
AIFslice has dimensions: `torch.Size([138, 138, 16])`

Indexing AIF slice by adding k*(t-1) element-wise to ind results in an out-of-bounds indexing error. Additionally, I'm not sure what purpose this particular step serves.

Any thoughts?

**Comment by aylward** [comment]
I think the conversion to pytorch and tensors is causing the problems.   Check the type of ROI.  Seems like the matlab code is expecting it to be a 1D array of values of length nC\*nR (the length of the array should equal the number of points in a 2D slice = 138\*138 = 19,044 for your case).  The values in that 1D array will be 0 everywhere except at the AIF points.   As tensors, the call to find() seems to be returning the x,y coordinates of the points, instead of returning the x+y\*nC indexes that correspond to the 1D version of those coordinates.    The code will probably work if you reshape ROI into a large, 1D array.

Find() will then return the indexes into the 1D array that contain non-zero values.   That is, the indexes into a reshaped slice that contain the AIF voxels.   Thereby ind should be a list whose length is the number of chosen points being considered as AIF points and who values are the indexes (in 1D) of those voxels.

K is the number of rows * number of columns = the size of a 2D slice once it is converted to a long 1D array.

The loop is going thru time (nT).   There are 16 time points in your case.

AIFSlice(x) should be a 1D reshape of the chosen slice for the AIF/ROI computation from every time point.   So, the first k values of AIFSlice should correspond to the ROI slice from time point 0.  The next k values in that 1D array should be the values from that same slice, but at time point 1.  The next k values should be time point 1...etc up to the final k values being the values from the last time point, i.e., time point 15 (for a total of 16 time points).   So the total size of AIFSlice should be nR\*nC*\nT = 138\*138\*16 for your case = 304,704 length.

Then, the loop is collecting the values at the AIF points (defined by ind) across time.  Time is computed by adding k\*(t-1) to those slice index values to move to the next time point (i.e., the next slice) with each iteration of the loop.   That is, the first iteration, it is using the ind values to gather the values at the AIF voxels for time point 0.   The next iteration of the loop is using the ind values + the size of a slice (k) to gather the values at the AIF voxel for time point 1, etc.

The size of datai2D should be 2D with the first dimension being the number of chosen AIF points and the second dimension being the number of time points = 16.

**Comment by aylward** [comment]
Looking more at the code,

line [466](https://github.com/peirong26/Perfusion-Analysis-Toolbox/blob/3927f9584feef711f97a3079dc29a230042391ed/utils/DSC_mri_aif.m#L466C1-L466C32) in DSC_mri_aif.m is

dati2D=zeros(sum(sum(ROI)),nT);

Assuming ROI has a value of 1 at AIF points and a value of 0 elsewhere, this allocates dati2D to be as I suggested, a 2D array with the first dimension being the number of chosen AIF points (the sum is the number of points having a value of 1) and the second dimension being the number of time points.

However, this also suggests that ROI is a 2D array.   I guess  ind = find(ROI) still returns a list of indexes into ROI (it treats ROI as if it is a long, 1D array) even though in this line it is being treated as a 2D array.   My matlab is rusty....looking at the documentation for find(), it say "If X is a multidimensional array, find returns a column vector of the linear indices of the result."   So, find() internally does the conversion from a 2D array to a linearly indexed 1D array and returns the non-zero indexes in that long 1D array.

So, ROI should be a 2D array, but find() returns the list of indexes into it, as if it was a long 1D array.

Similarly, AIFSlice might be a 3D array, but the code is accessing it as if it was a long 1D array.    You can do the conversions to / from 1D indexes and 2D points using k, nC, and nR.

**Comment by Caffetaria** [comment]
Ah thank you! That seems to be exactly what's being done. Testing this out!

**Comment by aylward** [comment]
It would be easy to keep all of this using 2d and 3d arrays in python.  The
numpy.where() function is a nice replacement for find.

S
